name: py-scripts
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - brotlipy=0.7.0
  - ca-certificates=2020.10.14
  - certifi=2020.6.20
  - cffi=1.14.4
  - chardet=4.0.0
  - cryptography=3.3.1
  - decorator=4.4.2
  - ffmpeg=4.3.1
  - freetype=2.10.4
  - idna=2.10
  - imageio=2.9.0
  - imageio-ffmpeg=0.4.3
  - intel-openmp=2020.3
  - jpeg=9d
  - libblas=3.9.0
  - libcblas=3.9.0
  - liblapack=3.9.0
  - libpng=1.6.37
  - libtiff=4.2.0
  - lz4-c=1.9.3
  - mkl=2020.4
  - moviepy=1.0.1
  - numpy=1.20.0
  - olefile=0.46
  - openssl=1.1.1i
  - pillow=8.1.0
  - pip=20.3.3
  - portaudio=19.6.0
  - proglog=0.1.9
  - pyaudio=0.2.11
  - pycparser=2.20
  - pyopenssl=20.0.1
  - pysocks=1.7.1
  - python=3.7.9
  - python_abi=3.7
  - requests=2.25.1
  - setuptools=52.0.0
  - six=1.15.0
  - speechrecognition=3.7.1
  - sqlite=3.33.0
  - tk=8.6.10
  - tqdm=4.56.0
  - urllib3=1.26.3
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.36.2
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.8
